### ISSUE TITLE
Various errors when executed.

### ISSUE THREAD

**Issue by DigitalCorrosion** [0xIslamTaha/Python-Rootkit#1]
Executed on Windows 7 - 32-bit.

Following errors are:

Traceback (most recent call last):
  File "GoogleChromeAutoLaunch.py", line 103, in <module>
  File "GoogleChromeAutoLaunch.py", line 33, in fire
  File "GoogleChromeAutoLaunch.py", line 62, in get_noip_ip_address
socket.gaierror: [Errno 11004] getaddrinfo failed

**Comment by DigitalCorrosion** [comment]
Seem's to be resolved when removing get_no_ip_address but does not call back home.

**Comment by DigitalCorrosion** [comment]
Fixed the issue. This can be closed.
