### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by Abdelghani19** [0xIslamTaha/Python-Rootkit#3]
Hi,
Try to convert the py source to exe using py2exe, with py3.10:
running py2exe
Traceback (most recent call last):
  File "C:\Python310\**setup.py**", line **51**, in <module>
    setup(
  File "C:\Python310\lib\site-packages\setuptools\__init__.py", line 153, in set
up
    return distutils.core.setup(**attrs)
  File "C:\Python310\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python310\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Python310\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Python310\lib\site-packages\py2exe\distutils_buildexe.py", line 204,
in run
    self._run()
  File "C:\Python310\lib\site-packages\py2exe\distutils_buildexe.py", line 284,
in _run
    builder.analyze()
  File "C:\Python310\lib\site-packages\py2exe\runtime.py", line 185, in analyze
    target.analyze(mf)
  File "C:\Python310\lib\site-packages\py2exe\runtime.py", line 84, in analyze
    modulefinder.run_script(self.script)
  File "C:\Python310\lib\site-packages\py2exe\vendor\modulefinder.py", line 201,
 in run_script
    self.load_module('__main__', fp, pathname, stuff)
  File "C:\Python310\lib\site-packages\py2exe\vendor\modulefinder.py", line 394,
 in load_module
    co = compile(fp.read(), m.__dest_file__, 'exec', optimize=self._optimize)
  File "__main__.pyc", line 71
    path = str(w[0]) + '\Chrome\User Data\Default\Login Data'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in positio
n 7-8: truncated \UXXXXXXXX escape

**Comment by Lebedev21** [comment]
If you can change ```path = str(w[0]) + '\Chrome\User Data\Default\Login Data'``` into ```path = str(w[0]) + r'\Chrome\User Data\Default\Login Data'```

**Comment by 0xIslamTaha** [comment]
last PR fixed this issue .. @Abdelghani19  could u verify it?
