### ISSUE TITLE
After running python setup.py py2exe i get error

### ISSUE THREAD

**Issue by IllegalLithium** [0xIslamTaha/Python-Rootkit#5]
after running python setup.py py2exe I get:              

running py2exe
C:\python27\setup.py:46: DeprecationWarning:
The `setup.py py2exe` command line interface is deprecated and
will be removed in the next major release.

Please adapt your code to use the new `py2exe.freeze` API.

Further information can be found at
https://github.com/py2exe/py2exe/blob/master/README.md

  setup(
running build_py
Traceback (most recent call last):
  File "C:\python27\setup.py", line 46, in <module>
    setup(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\py2exe\distutils_buildexe.py", line 204, in run
    self._run()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\py2exe\distutils_buildexe.py", line 284, in _run
    builder.analyze()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\py2exe\runtime.py", line 185, in analyze
    target.analyze(mf)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\py2exe\runtime.py", line 84, in analyze
    modulefinder.run_script(self.script)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\py2exe\vendor\modulefinder.py", line 201, in run_script
    self.load_module('__main__', fp, pathname, stuff)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\py2exe\vendor\modulefinder.py", line 393, in load_module
    co = compile(fp.read(), m.__dest_file__, 'exec', optimize=self._optimize)
  File "__main__.pyc", line 71
    path = str(w[0]) + '\Chrome\User Data\Default\Login Data'
                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 7-8: truncated \UXXXXXXXX escape

please fix this

**Comment by peggy-48** [comment]
*btw this isn't an actual rootkit but a backdoor*
*sound intensifies*
Yeah i think you got scammed.

**Comment by maximus-sallam** [comment]
> _btw this isn't an actual rootkit but a backdoor_ _sound intensifies_ Yeah i think you got scammed.

It's actually a RAT + backdoor. But you're right, it definitely isn't a root kit. Scammed out of a what though? What did he lose?

**Comment by peggy-48** [comment]
His time

**Comment by maximus-sallam** [comment]
Touche 😂

**Comment by peggy-48** [comment]
Oui

**Comment by 0xIslamTaha** [comment]
seems I missed the party 😂 
Actually, I developed it just out of curiosity . I think this project is too old now pretty sure that most of the antivirus already has it's footprint ..

happy to receive PRs ..
